### ISSUE TITLE
Error in GCN layer training 

### ISSUE THREAD

**Issue by IbtihalFerwana** [pkuyzy/TLC-GNN#3]
Hello @pkuyzy 

I am trying to reproduce your code for datasets `Photo` and `Computers` I faced an error in GCN, using the command `!python pipelines.py` 
The traceback:
```
Traceback (most recent call last):
  File "pipelines.py", line 122, in <module>
    pred = train()
  File "pipelines.py", line 14, in train
    emb = model.encode(data)
  File "/TLC-GNN/baselines/TLCGNN.py", line 22, in encode
    x = F.relu(self.conv1(x, edge_index))
RuntimeError: Sizes of tensors must match except in dimension 0. Got 2 and 651997 (The offending index is 0)
```
Did you need to make any changes to the edges size or nodes?

Do you have a complete running example for any of the datasets?

**Comment by pkuyzy** [comment]
You can try to print the dimension of x and edge_index, and see whether the dimension is right. X should be a |V| * d tensor, where |V| is the number of nodes, and d is the dimension of feature vectors. Edge_index should be a 2*|E| tensor, where |E| is the number of edges.
